[package]
name = "gb7"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gb7-core = { path = "../gb7-core" }
pixels = "0.10.0"
winit = "0.27.5"
