[package]
name = "gb7-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
enum_dispatch = "0.3.8"
lazy_static = "1.4.0"
memmap2 = "0.5.8"
test-case = "2.1.0"
